# vim provisioning/roles/criando-instancias/vars/main.yml
---
# vars file for criando-instancias
instance_type: t2.medium
sec_group_name: giropops
image: ami-085925f297f89fce1
keypair: ansible-class
region: us-east-1 
count: 3
profile: giropops
